worker_processes auto;
events { worker_connections 1024; }

http {
    server {
        # Redirect all HTTP traffic to HTTPS
        listen 80;
        # NOTE: server_name must match the DOMAIN_NAME variable in .env
        # NGINX does not support environment variable substitution in config files.
        # Replace this value manually when deploying to a different domain.
        server_name DOMAIN_NAME;

        location / {
            add_header Access-Control-Allow-Headers "Content-Type" always;
	    return 308 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        # NOTE: server_name must match the DOMAIN_NAME variable in .env
        # NGINX does not support environment variable substitution in config files.
        # Replace this value manually when deploying to a different domain.
        server_name DOMAIN_NAME;

        # SSL configuration
        ssl_certificate /etc/nginx/certs/grafana.crt;
        ssl_certificate_key /etc/nginx/certs/grafana.key;

        # Security headers (optional, but recommended)
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;

	# Reverse proxy for Grafana
        location /monitor-grafana/ {
            proxy_pass http://monitor-grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Reverse proxy for FIWARE IoT-Agent
        location /iot-agent/ {
            proxy_pass http://fiware-iot-agent:7896/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

	# Reverese proxy for FastAPI ML service.
	location /predict {
            proxy_pass http://fastapi-ml:8000/predict;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Default catch-all for errors
        error_page 404 /404.html;
    }
}

